# Generated by Django 5.1.2 on 2026-04-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('peak_count', models.IntegerField(default=0)),
                ('avg_count', models.FloatField(default=0.0)),
                ('total_unique', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('total_snapshots', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CrowdSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('people_count', models.IntegerField(default=0)),
                ('cumulative_count', models.IntegerField(default=0)),
                ('mode', models.CharField(default='human', max_length=10)),
                ('density_alert', models.BooleanField(default=False)),
                ('weapon_alert', models.BooleanField(default=False)),
                ('fire_alert', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='surveillance.surveillancesession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
